name: Checkout code
on:
    workflow_dispatch:

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Checkout code
              uses: actions/checkout@v2