# This workflow runs when a PR is created, and will verify that
# no deprecated Node.js versions are used in the workflow actions.
name: Check Node Version in GitHub Actions

on: pull_request

jobs:
  check-node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo pip install yq

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for deprecated Node.js versions in workflows
        run: $GITHUB_WORKSPACE/.github/check-for-deprecated-node-versions.sh